CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50),
    last_login TIMESTAMP,
    joined_at TIMESTAMP,
    updated_at TIMESTAMP,
    recovery_email VARCHAR(255),
    last_old_password VARCHAR(255),
    employee_id BIGINT,
    client_id BIGINT
);

INSERT INTO roles (role_name) VALUES ('common_user');
INSERT INTO roles (role_name) VALUES ('premium_user');
INSERT INTO roles (role_name) VALUES ('storage_manager');
INSERT INTO roles (role_name) VALUES ('cashier');
INSERT INTO roles (role_name) VALUES ('admin');
