-- Create Physical Sales Table
CREATE TABLE physical_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_date TIMESTAMP,
    subtotal NUMERIC,
    discount NUMERIC,
    total NUMERIC,
    client_id BIGINT,
    employee_id BIGINT,
    employee_name VARCHAR(255),
    pay_type VARCHAR(50),
    sale_status VARCHAR(50)
);

-- Create Physical Sale Items Table
CREATE TABLE physical_sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    product_name VARCHAR(255),
    product_unit_price NUMERIC,
    product_quantity INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    physical_sale_id BIGINT,
    FOREIGN KEY (physical_sale_id) REFERENCES physical_sales(id) ON DELETE CASCADE
);


-- Insert into physical_sales
INSERT INTO physical_sales (sale_date, subtotal, discount, total, client_id, employee_id, employee_name, pay_type, sale_status) VALUES
(CURRENT_TIMESTAMP, 9.99, 0, 9.99, 1, 1, 'John Doe', 'CARD', 'COMPLETED'),
(CURRENT_TIMESTAMP, 15.99, 0, 15.99, 2, 2, 'Jane Smith', 'CASH', 'COMPLETED'),
(CURRENT_TIMESTAMP, 24.99, 0, 24.99, 3, 3, 'Emily Johnson', 'CARD', 'COMPLETED'),
(CURRENT_TIMESTAMP, 8.99, 0, 8.99, 4, 4, 'Michael Brown', 'CASH', 'COMPLETED'),
(CURRENT_TIMESTAMP, 12.99, 0, 12.99, 5, 5, 'Sarah Davis', 'CARD', 'COMPLETED'),
(CURRENT_TIMESTAMP, 4.99, 0, 4.99, 6, 6, 'David Wilson', 'CASH', 'COMPLETED'),
(CURRENT_TIMESTAMP, 3.99, 0, 3.99, 7, 7, 'Laura Miller', 'CARD', 'COMPLETED'),
(CURRENT_TIMESTAMP, 7.99, 0, 7.99, 8, 8, 'Robert Taylor', 'CASH', 'COMPLETED'),
(CURRENT_TIMESTAMP, 10.99, 0, 10.99, 9, 9, 'Jessica Anderson', 'CARD', 'COMPLETED'),
(CURRENT_TIMESTAMP, 22.99, 0, 22.99, 10, 10, 'Daniel Martinez', 'CASH', 'COMPLETED');

-- Insert into physical_sale_items
INSERT INTO physical_sale_items (product_id, product_name, product_unit_price, product_quantity, created_at, physical_sale_id) VALUES
(1, 'Extra Strength Tylenol', 9.99, 1, CURRENT_TIMESTAMP, 1),
(2, 'Neutrogena Hydro Boost', 15.99, 1, CURRENT_TIMESTAMP, 2),
(3, 'Pampers Swaddlers', 24.99, 1, CURRENT_TIMESTAMP, 3),
(4, 'Robitussin Cough Syrup', 8.99, 1, CURRENT_TIMESTAMP, 4),
(5, 'Centrum Adult Multivitamin', 12.99, 1, CURRENT_TIMESTAMP, 5),
(6, 'Band-Aid Flexible Fabric Adhesive Bandages', 4.99, 1, CURRENT_TIMESTAMP, 6),
(7, 'Colgate Total Whitening Toothpaste', 3.99, 1, CURRENT_TIMESTAMP, 7),
(8, 'Advil Liqui-Gels', 7.99, 1, CURRENT_TIMESTAMP, 8),
(9, 'Cetaphil Gentle Skin Cleanser', 10.99, 1, CURRENT_TIMESTAMP, 9),
(10, 'Huggies Little Snugglers', 22.99, 1, CURRENT_TIMESTAMP, 10);
