server:
  port: ${ADMIN_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health, info

spring:
  application:
    name: admin-service
  boot:
    admin:
      discovery:
        enabled: true

      client:
        instance:
          prefer-ip: true
          service-base-url: http://localhost:8080
          management-base-url: http://localhost:8080/actuator

