global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "address-service"
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ["address-service:8080"]
